[tool.poetry]
name = "iesb-projeto-integrador-ii"
version = "0.1.0"
description = ""
authors = ["borges"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.2"
requests = "^2.32.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
