services:
  postgres:
    image: postgres:16.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    expose:
    - 5433
    ports:
      - 5433:5432
    volumes:
      - ${PWD}/docker/postgres/scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - dev

  notebook:
    image: jupyter/pyspark-notebook:spark-3.1.2
    ports:
      - "8888:8888"
    volumes:
      - ${PWD}/app/analytics:/home/jovyan/notebooks
    networks:
      - dev

networks:
  dev:
    driver: bridge